"""Core layer for backtest engine, performance metrics, configuration, logging, and event system."""

from backtester.core.backtest_engine import BacktestEngine
from backtester.core.config import (
    BacktesterConfig,
    BacktestRunConfig,
    ComprehensiveRiskConfig,
    DataConfigView,
    DataRetrievalConfig,
    ExecutionConfig,
    PerformanceConfig,
    PortfolioConfig,
    PortfolioConfigView,
    RiskConfigView,
    StrategyConfig,
    build_data_config_view,
    build_portfolio_config_view,
    build_risk_config_view,
    get_config,
    reset_config,
    set_config,
)

# Event system imports
from backtester.core.config_diff import ConfigDelta, diff_configs, format_config_diff
from backtester.core.config_processor import (
    ConfigProcessor,
    ConfigProcessorError,
    ConfigSourceError,
    ConfigValidationError,
)
from backtester.core.event_bus import Event, EventBus, EventFilter, EventPriority
from backtester.core.event_handlers import (
    CompositeEventHandler,
    EventHandler,
    MarketDataHandler,
    OrderHandler,
    PortfolioHandler,
    RiskHandler,
    SignalHandler,
    StrategyHandler,
    create_event_handler,
)
from backtester.core.events import (
    BacktestEvent,
    DataUpdateEvent,
    MarketDataEvent,
    MarketDataType,
    OrderEvent,
    OrderSide,
    OrderStatus,
    OrderType,
    PerformanceEvent,
    PortfolioUpdateEvent,
    RiskAlertEvent,
    RiskLevel,
    SignalEvent,
    SignalType,
    StrategyEvent,
    StrategyEventType,
    create_market_data_event,
    create_order_event,
    create_portfolio_update_event,
    create_risk_alert_event,
    create_signal_event,
    create_strategy_event,
)
from backtester.core.interfaces import (
    BrokerProtocol,
    PortfolioProtocol,
    RiskManagerProtocol,
    StrategyProtocol,
)
from backtester.core.logger import bind_logger_context, get_backtester_logger
from backtester.core.performance import OperationalMetrics, PerformanceAnalyzer

__all__ = [
    # Core components
    'BacktestEngine',
    'BacktesterConfig',
    'BacktestRunConfig',
    'ComprehensiveRiskConfig',
    'ConfigProcessor',
    'ConfigProcessorError',
    'ConfigSourceError',
    'ConfigValidationError',
    'DataRetrievalConfig',
    'DataConfigView',
    'StrategyConfig',
    'PortfolioConfig',
    'PortfolioConfigView',
    'ExecutionConfig',
    'PerformanceConfig',
    'RiskConfigView',
    'get_config',
    'set_config',
    'reset_config',
    'build_data_config_view',
    'build_portfolio_config_view',
    'build_risk_config_view',
    'ConfigDelta',
    'diff_configs',
    'format_config_diff',
    'bind_logger_context',
    'get_backtester_logger',
    'PerformanceAnalyzer',
    'OperationalMetrics',
    'StrategyProtocol',
    'PortfolioProtocol',
    'BrokerProtocol',
    'RiskManagerProtocol',
    # Event system
    'EventBus',
    'Event',
    'EventFilter',
    'EventPriority',
    # Event types
    'MarketDataEvent',
    'SignalEvent',
    'OrderEvent',
    'PortfolioUpdateEvent',
    'RiskAlertEvent',
    'StrategyEvent',
    'BacktestEvent',
    'DataUpdateEvent',
    'PerformanceEvent',
    'MarketDataType',
    'SignalType',
    'OrderType',
    'OrderSide',
    'OrderStatus',
    'RiskLevel',
    'StrategyEventType',
    # Event factories
    'create_market_data_event',
    'create_signal_event',
    'create_order_event',
    'create_portfolio_update_event',
    'create_risk_alert_event',
    'create_strategy_event',
    # Event handlers
    'EventHandler',
    'MarketDataHandler',
    'SignalHandler',
    'OrderHandler',
    'PortfolioHandler',
    'RiskHandler',
    'StrategyHandler',
    'CompositeEventHandler',
    'create_event_handler',
]
